require:
  - standard
  - rubocop-minitest
  - rubocop-rake

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  EnabledByDefault: true
  Exclude:
    - vendor/bundle/**/*

Style/FrozenStringLiteralComment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: true
