#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["RACK_ENV"] ||= if ARGV.first == "build"
  "production"
else
  "development"
end

base_path = File.expand_path("../lib", __dir__)

if File.exist?(base_path)
  require_relative "../lib/statique"
else
  require "statique"
end

Statique.ui.info "Statique", version: Statique::VERSION, environment: ENV["RACK_ENV"]

Statique::CLI.start
