#!/usr/bin/env -S ruby --yjit -w --enable=frozen-string-literal

base_path = File.expand_path("../lib", __dir__)

if File.exist?(base_path)
  require_relative "../lib/statique"
  require_relative "../lib/statique/cli"
else
  require "statique"
  require "statique/cli"
end

Statique::CLI.start
