name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake test

    - name: Build gem
      run: bundle exec rake build

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get Ruby version
      id: ruby_version
      run: echo "::set-output name=ruby-version::$(cat .ruby-version | tr -d '\n')"

    - name: Get Statique version
      id: statique_version
      run: echo "::set-output name=statique-version::$(ruby -Ilib/statique -r version -e 'print Statique::VERSION')"

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        build-args: |
          RUBY_VERSION=${{ steps.ruby_version.outputs['ruby-version'] }}
          STATIQUE_VERSION=${{ steps.statique_version.outputs['statique-version'] }}
        tags: |
          pusewicz/statique:latest
          pusewicz/statique:${{ steps.statique_version.outputs['statique-version'] }}
